# ubuntu trusty has g++-1.48 and boost-1.54
dist: trusty

language: python
python: 
  - "2.7"
  - "3.5"
  - "3.7"

notifications:
  email: false

install:
#  - pip install .
  - python setup.py develop
  
script:
  - pytest
  
addons:
  apt:
    packages:      
      - libboost-program-options-dev
      
cache:
  - apt
  - pip
